dist: xenial
sudo: false
latex: false
language: r
r: release

warnings_are_errors: false

cache:
  packages: true

apt_packages:
  - libgdal-dev
  - libudunits2-dev

git:
  depth: false

r_packages:
  - shiny
  - shinythemes
  - DT
  - plotly
  - zoo

script:
  - R -f deploy.R

env:
  global:
  - secure: Hsrf7Fc6kVeyyJezMvm2wsXJDWy6QQYdbo08RB0rbCHh1ESwEckGaLeDPwPik5aDc0Kb7E/fKvWjof1xmZ4LhCBosF/NFZeHoa941sZmMg8k7jniHtoo0aEOPQ26ryHsrnmJ7O6s3E+CVEefZuDQxTORfE3eQMynhvgEWsUiRc23SGV1oWmCvSDHPXlEfsHayITzFqHGYKM60XUBvhbGrW1QmTV1WdsYEvx5CkJLaEBqYIpSOkf98LKiqpdMDPzMOXkVpk6N0z7j1S0Qb6WW6HxrdZR8GSAHCUMwF6pipG2ImixRoTeT3+vHN8OdIrY80jCh2GV/MxxCVfw/nBe2abQ9XVM74jAbBqSu4be9gSROd0gLpj2kZeCE+v747BHg/iyf30VHVWZp30MA1lDYv/ArHI/jgTPgO8KT24aKug6IxoYtJCxNcmuqHb2h42qlT5esrTkJRFlHOnxhOQAJEQXfybfit2D6/gXyQn7o3KxM969Zlx/Nbhl26tWEjOoXRCkhkQcMaWtIwPc9XpdRhXR6LjKh5EGP62eyJoj5KWe66Q2rrPb8kSYlVAfmf/7tJYOGR9352gLl959wh44q1cXcMoQwpWU+h2j3XypejyW5TMDadT/c+vdchvAJcU4g0yBJHoJXQQColxLo0l0dPiD9/ZM45UEMJPQlmFe2eOI=
  - secure: YlyxtXEer/tN8kgtiNQ4jMT6IGS7IBU7Cu3FHf1TdZ41uVrVQTG+AVwdi/66c0UHIml7CYrXfMWe+nL9YmxGs5VsPNaJ7Tw0ui1aPHD6OIJ2AASFQOhSENMgX6xifGDG/PFj8owsAw1hJeWRXxGWwNmyp9/AGib16HvQSa95bwxlNFLX3fbIN6nrN+zBvCA7K02krW27H8aurVCsKRfTwyQh2EUNKMEwOPkEC9tS0fgQMZrTZT0XKhq7TWEHTOgauou0YZp/0vtawiUGvJYZcByLXel3k/FIfe6VW3xuzzGBQEOt529TcutzK+qfazKg/dXSTL+Gz/etdE0DLDm8qce2hqU8WvC+r08kSWO/odlSPXbmi94Qh4zAKZFmYUdBmeuHNiDAcmkGeyIwEGYxISugKfiMbUL7EWYWOUhvqqXvXETqGg790O/+zaEVZvdl1cvlITMhh6Mk0YFx+6RdCGScVUEex4OYgKnaOowVhjKN18sZ9Hq6ZFk8LD+bY7832O8tXbN7usRd0dvUBwEyicyhHSOHe3kE83y+3J9EE3rFkjp74QWR7Q9XwR07UpQzCeWzt8c8rBp5YMaKkt8CxkbW6MS29rrBTfrbe6dvWQneNchqJj5ypzrED2CbS6HOE066izyQfaVKinxdSqp9mMHXH5ia7y/EPD3MS6YcpR4=
  - secure: ADgMRpeQ/YKASKgPVCM9GnmSlghUmo0J+RZrX6V/Vot7hWwhu+y2+vnE9mSKl4xnbV+6+jXFzZf/EtZwv/D03PXqSCmoqKGMC08PN+V2NAunp6rQgvw9/JFLYzRAURXmjB11rmAapNM+S3ibpweGjllViu0+2LNmOS4qDfCJq0liuNIuX7o3C/BQbUriGXvFt6qosEddSTw1ruQnbgXwKKfyWILBNb8fvv9B3WczH53PZaKiYdxWIokI5ORM/XRKiO/ILMaluA7Fw6QQ6SGVPbzjH44lGSaTgiBGqexJqz9EYjWEIxbNtbNb+m9B6/sg1Wf6pXkEBQrUFdn//bcOfWkB9+nyQw1AhhFzfLd3pXXw6DPtpRPKiV8Vi+5olbWIdwQJ0UCjh6pXWy4Q7MQmUsv/1ywR+isa6wJFLmVAaej+oVoW6rLPCZ0hzGwJJlW5IVI421ESvTgV36gCD/3djKuXkIlT0OndaRdxQMzRqyg1R2kuHF3l6G9uAJM6Ezsc5m221Jq9RaZUtOEg7YNYyyLFcSjPwUDaccPggB92MkL6YY4cIOrA75U3yCs66VzxlXb71cNu9U5el0p0hc4YDR5Y9U7cF9uQr/c2QefBXdnNBkXfM2rN8kXx3kChDQqfPSaFDvWYzpIdPY7cgU6hg8GxVAfIdCNblZNBJGGyJ7k=
  - secure: FE83G3+Xti+SJdzaiiTtnMXZRObngsWHDp0N9TZsqXrrAQjfnN+ihDZKq4L9KHVYQATx02w+9xcf/jOlOjNYvZgoHNjrDi3wzM5/mqHLzJhtRdtMJLWjt0iipwc3I/IjuaZq9RVQMxpRJg/egtjlAWAgmIc7hmP2AMt2cLEc7Xne7KJaNiAjRIbJVqjxz306HB3E3/Rhup5PXR0qsk5ZC35EtMFU+zlEsWKNTuJtZ5W003Z52ATsIj58OuK6VcHG/a4Vg+fRJR+rowy6Fg8z7O5LewDzZ393z+wpTMqSKhoYp6Foj1SfBVlcxai1lpBC+TrJ7m1vl1Tzm97JfDGSE0kkOoUqXzTmYJ6LlY9k0Fa4Z71bkWxh5bAhtePbZMX48dkBDtiLKjyVtPT8dyBrIBaI6qXj9B1q12iKmCE+CDgacsn9I8w8r6fQ0WCkD+3U+t/l8ehSby38fwN2WdvZE+JSfsyBb1HzcRsIc2S+FjxFtMIuvxlpge1+8M0vusA9S/z7qGnq6jkiEfdq+Cn9RNAVyTarYrIC0uVxEBQ/U/MxIJgk9Dd8T3gU2TjARlXamhQfDk0ctR1rpsj9xvjRUR3zoIrc03zUVtLWSPdBG/TuVQRVpf8qEvOU0oEU7ksKcpcItz443dLt4qEW5hYx9Uf3WYyihnRcKRAjKAq5lG0=
